### ISSUE TITLE
client hangs after failed upload

### ISSUE THREAD

**Issue by bhamon** [mercurius-js/mercurius-upload#13]
I'm using mercurius + mercurius-upload with a basic mutation resolver that reads an input file to store it to a S3 bucket.
If the resolver fails all the subsequent requests to fastify hang indefinitely.

You can find a minimal reproduction code here: https://github.com/bhamon/bug-graphql-upload

To reproduce the issue you should use Chrome + upload a file of about 300 KB (smaller files doesn't fail).
The issue can be reproduced with other clients too, but depending on the client and the uploaded file the results varies a lot. The client must reuse the same HTTP stream in order for the problem to occurs.

The issue as already been reported [here](https://github.com/jaydenseric/graphql-upload/issues/152) for Apollo server and a corrective PR has been issued.

I'm not very familiar with Fastify internals so I can only assume that the problem should be the same.

**Comment by SimenB** [comment]
> 3\. `mercurius-upload` has not been updated to the latest Mercurius and it's stuck on v10.

We use `mercurius-upload` with Mercurius v11 successfully, FWIW (and also with `@apollo/server` and `@as-integrations/fastify`). Haven't attempted to upgrade to v12, but OP uses v11, so probably won't make a difference.

> This module is missing the equivalent of [this line](https://github.com/jaydenseric/graphql-upload/blob/e01b5d5541760d529b06c900883c5fa7febcff00/graphqlUploadKoa.mjs#L51), i.e. we should wait for the request to be fully consumed before sending a response.

Adding that should be somewhat straightforward, unless I'm missing something. I'd assume an `await stream.promises.finished(request.raw)` (or possibly `await events.once(request.raw, 'end')`?) should work?

> Another problem that I can't use `mercurius-upload` because this package is made for `fastify` v3, I use v4

This is incorrect.

https://github.com/mercurius-js/mercurius-upload/blob/3a91963edacea239f2b9370e8f18e839c0f29ea9/index.ts#L36

I see the readme is wrong, though: https://github.com/mercurius-js/mercurius-upload/pull/12

**Comment by mcollina** [comment]
I can see something like that should work @SimenB.

@Jawell would you like to try fixing this?

**Comment by Jawell** [comment]
Sure, I'll try to use this advice, stay in touch

**Comment by mcollina** [comment]
I think you should place an `await events.once(request.raw, 'end')` inside an `onSend` Fastify hook.

**Comment by Jawell** [comment]
So, I tried this and it would be enough:
```
  fastify.addHook('onSend', async function (request) {
    if (!request.mercuriusUploadMultipart) {
      return
    }

    await promises.finished(request.raw)
  })
```
I'll create PR with tests later today. Or you want to use `events.once`? But I didn't catch what is `events`

**Comment by SimenB** [comment]
> But I didn't catch what is `events`

`require('events')`

**Comment by climba03003** [comment]
It is a simple function and I would avoid promise most of the time.
You can use the done callback without async-await.

**Comment by SimenB** [comment]
Closed via #14

**Comment by PabloSzx** [comment]
> Closed via #14

**Comment by sammwafy** [comment]
The same error persists after switching to graphql-upload-minimal.
Changing the import of processRequest to be from graphql-upload or graphql-upload-ts resolved the issue for me.

**Comment by amazzoccone** [comment]
Same error as @sammwafy :disappointed: . Fix it as mentioned:
```
import processRequest from 'graphql-upload/processRequest.mjs'
```
Would be great to revert usage of graphql-minimal-upload or fix implementation.

**Comment by ceopaludetto** [comment]
Same as @sammwafy, replacing `graphql-upload-minimal` with `graphql-upload-ts` just works. In my case a guard in NestJS was throwing an error and mercurius just hanged forever, replacing via a patch did the work. The diff in the file `mercurius-upload/dist/index.js`
```diff
diff --git a/dist/index.js b/dist/index.js
index 702d96f368943c6030dd1f801b66efb47ac7553a..35640696bf121ece6997f149264edf8d47366d31 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -30,7 +30,7 @@ exports.mercuriusUpload = void 0;
 const util = __importStar(require("util"));
 const stream_1 = __importDefault(require("stream"));
 const fastify_plugin_1 = __importDefault(require("fastify-plugin"));
-const graphql_upload_minimal_1 = require("graphql-upload-minimal");
+const graphql_upload_minimal_1 = require("graphql-upload-ts");
 const finishedStream = util.promisify(stream_1.default.finished);
 const mercuriusGQLUpload = (fastify, options, done) => {
     fastify.addContentTypeParser('multipart', (req, _payload, done) => {
```

You also need to replace every usage of `graphql-upload-minimal` to `graphql-upload-ts` in your application (scalars and types)

**Comment by capJavert** [comment]
This is indeed an issue even if latest code was to be released https://github.com/mercurius-js/mercurius-upload/pull/24#issuecomment-2442001808 it still hangs without @ceopaludetto patch.

**Comment by belmeopmenieuwesim** [comment]
This issue should be re-opened. Still an issue when using `graphql-upload-minimal`. 

If the createReadStream is not consumed, then it will hang forever. This is a major issue when you have application errors/exceptions, that could happen before consuming createReadStream. I would advise to indeed use graphql-upload-ts or something else.
